spring:
  application:
    name: sample-service-rest
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
    username: root
    password: changeme
logging:
  config: classpath:log4j2.xml
